# -*- coding: utf-8 -*-
"""ScreenshotPage.tsx：进度条就地展开 + 停止下载 + 删除模型。保 CRLF。"""
P = r"D:/My-Custom-Tool/Xiaoxin-Tool-Box/src/settings/ScreenshotPage.tsx"
with open(P, encoding="utf-8", newline="") as f:
    raw = f.read()
nl = "\r\n" if "\r" in raw else "\n"
L = raw.split(nl)

# ---- import 区 ----
i = L.index('import { useEffect, useRef, useState } from "react";')
assert L[i + 1].startswith("import { useConfigStore }")
assert L[i + 2].startswith("import { ocrModelDownload")
L[i:i + 3] = [
    'import { Fragment, useEffect, useRef, useState } from "react";',
    'import { useConfigStore } from "../stores/configStore";',
    'import { ocrModelCancel, ocrModelDelete, ocrModelDownload, ocrModelStatus, shotHistoryClear, OCR_DL_EVENT, type OcrModelInfo, type OcrDlProgress } from "../core/tauri";',
    'import { listen, type UnlistenFn } from "@tauri-apps/api/event";',
]

# ---- 组件整段重写 ----
s = L.index("/** 文字识别模型档位：切档即时生效；未下载的档位先下载、成功后再启用 */")
e = next(k for k in range(s, len(L)) if L[k] == "}")
new_comp = [
    "/** 文字识别模型档位：切档即时生效；未下载的档位先下载、成功后再启用 */",
    "function OcrModelRows() {",
    "  const config = useConfigStore((s) => s.config);",
    "  const update = useConfigStore((s) => s.update);",
    "  const [models, setModels] = useState<OcrModelInfo[] | null>(null);",
    "  const [busy, setBusy] = useState<string | null>(null);",
    "  const [err, setErr] = useState(\"\");",
    "  const [prog, setProg] = useState<OcrDlProgress | null>(null);",
    "  const [deleting, setDeleting] = useState<string | null>(null);",
    "  // 瞬时速率测算：相邻两次进度事件（download 阶段）的字节差 / 时间差",
    "  const lastTick = useRef<{ t: number; done: number } | null>(null);",
    "  const [speed, setSpeed] = useState(0);",
    "  // 「停止」主动取消标记：Rust 侧 Err 回来时用于区分取消与真失败",
    "  const cancelReq = useRef(false);",
    "",
    "  useEffect(() => {",
    "    ocrModelStatus().then(setModels).catch(() => setModels([]));",
    "    let un: UnlistenFn | null = null;",
    "    void listen<OcrDlProgress>(OCR_DL_EVENT, (e) => {",
    "      const p = e.payload;",
    "      setProg(p);",
    "      const now = Date.now();",
    "      if (p.phase === \"download\") {",
    "        const prev = lastTick.current;",
    "        if (prev) {",
    "          const dt = (now - prev.t) / 1000;",
    "          const dd = p.done - prev.done;",
    "          if (dt > 0.1 && dd >= 0) setSpeed(dt > 0 ? Math.max(0, dd / dt) : 0);",
    "        }",
    "        lastTick.current = { t: now, done: p.done };",
    "      } else if (p.phase === \"done\") {",
    "        lastTick.current = null;",
    "        setSpeed(0);",
    "      }",
    "    }).then((f) => { un = f; }).catch(() => {});",
    "    return () => { if (un) un(); };",
    "  }, []);",
    "",
    "  const resetDl = () => {",
    "    setBusy(null);",
    "    setProg(null);",
    "    lastTick.current = null;",
    "    setSpeed(0);",
    "  };",
    "",
    "  const pick = async (m: OcrModelInfo) => {",
    "    if (m.active || busy) return;",
    "    setErr(\"\");",
    "    if (!m.ready) {",
    "      cancelReq.current = false;",
    "      setBusy(m.id);",
    "      setProg(null);",
    "      lastTick.current = null;",
    "      setSpeed(0);",
    "      try {",
    "        setModels(await ocrModelDownload(m.id));",
    "      } catch (e) {",
    "        // 主动取消不算失败，静默复位（半成品已保留，下次接着下）",
    "        if (cancelReq.current) {",
    "          cancelReq.current = false;",
    "          resetDl();",
    "          return;",
    "        }",
    "        setErr(e instanceof Error ? e.message : String(e));",
    "        resetDl();",
    "        return;",
    "      }",
    "      resetDl();",
    "    }",
    "    // 等配置写入+广播完成，Rust 侧 set_model 才会生效；",
    "    // 之后再刷一次状态列表，让\"使用中\"标记即时更新",
    "    await update({ ...config, shot: { ...config.shot, ocr_model: m.id } });",
    "    setModels(await ocrModelStatus());",
    "  };",
    "",
    "  // 停止下载：Rust 置取消旗标，半成品保留，下次从断点接着下",
    "  const stop = () => {",
    "    cancelReq.current = true;",
    "    void ocrModelCancel().catch(() => {});",
    "    resetDl();",
    "  };",
    "",
    "  // 删除档位模型（数据目录内；使用中拒删；共用文件保留）",
    "  const del = async (m: OcrModelInfo) => {",
    "    setErr(\"\");",
    "    try {",
    "      setModels(await ocrModelDelete(m.id));",
    "    } catch (e) {",
    "      setErr(e instanceof Error ? e.message : String(e));",
    "    }",
    "  };",
    "",
    "  if (!models) return null;",
    "  const dl = prog && busy === prog.id ? prog : null;",
    "  const mb = (b: number) => (b > 0 ? `${(b / 1048576).toFixed(1)} MB` : \"…\");",
    "  const fileLabel = (f: string) =>",
    "    f.includes(\"det\") ? \"检测模型\" : f.includes(\"rec\") ? \"识别模型\" : \"字典\";",
    "  const pct = dl && dl.total > 0 ? Math.min(100, (dl.done / dl.total) * 100) : null;",
    "  const speedTxt = speed > 0 ? ` · ${(speed / 1048576).toFixed(1)} MB/s` : \"\";",
    "  const redBtn = { background: \"#e5484d\", color: \"#fff\", borderColor: \"#e5484d\" };",
    "  return (",
    "    <SettingGroup>",
    "      <SettingRow",
    "        title=\"文字识别模型\"",
    "        desc={err ? `模型下载失败：${err}` : \"离线识别，切换后立即生效；档位越高越准，但体积更大、识别更慢\"}",
    "      />",
    "      {models.map((m) => (",
    "        <Fragment key={m.id}>",
    "          <SettingRow",
    "            title={m.active ? `${m.name}（使用中）` : m.name}",
    "            desc={`${m.desc} · 约 ${m.size_mb}MB${m.ready ? \"\" : \" · 未下载\"}`}",
    "          >",
    "            {m.active ? (",
    "              <button className=\"btn btn-sm\" disabled>使用中</button>",
    "            ) : busy === m.id ? (",
    "              <button className=\"btn btn-sm\" style={redBtn} onClick={stop}>停止</button>",
    "            ) : (",
    "              <>",
    "                <button className=\"btn btn-sm\" disabled={busy !== null} onClick={() => void pick(m)}>",
    "                  {m.ready ? \"启用\" : \"下载并启用\"}",
    "                </button>",
    "                {m.ready && (",
    "                  <button",
    "                    className=\"btn btn-sm\"",
    "                    disabled={busy !== null}",
    "                    style={deleting === m.id ? redBtn : undefined}",
    "                    onClick={() => {",
    "                      if (deleting === m.id) {",
    "                        setDeleting(null);",
    "                        void del(m);",
    "                      } else {",
    "                        setDeleting(m.id);",
    "                        window.setTimeout(() => setDeleting((cur) => (cur === m.id ? null : cur)), 3000);",
    "                      }",
    "                    }}",
    "                  >",
    "                    {deleting === m.id ? \"确认删除\" : \"删除\"}",
    "                  </button>",
    "                )}",
    "              </>",
    "            )}",
    "          </SettingRow>",
    "          {dl && dl.id === m.id && (",
    "            <SettingRow",
    "              layout=\"block\"",
    "              title={`${m.name} 下载中…`}",
    "              desc={",
    "                dl.phase === \"verify\"",
    "                  ? \"正在校验文件完整性，马上就好\"",
    "                  : dl.total > 0",
    "                    ? `${mb(dl.done)} / ${mb(dl.total)}${speedTxt}`",
    "                    : `${mb(dl.file_done)}${speedTxt}`",
    "              }",
    "            >",
    "              <div className=\"ocr-dl\">",
    "                <div className=\"ocr-dl-track\">",
    "                  <div",
    "                    className={`ocr-dl-fill${pct === null ? \" indet\" : \"\"}`}",
    "                    style={pct !== null ? { width: `${pct}%` } : undefined}",
    "                  />",
    "                </div>",
    "                <div className=\"ocr-dl-meta\">",
    "                  {dl.phase === \"verify\"",
    "                    ? \"SHA256 完整性校验\"",
    "                    : `正在下载${fileLabel(dl.file)}`}",
    "                  {dl.phase === \"download\" && dl.file_total > 0",
    "                    ? ` · ${mb(dl.file_done)} / ${mb(dl.file_total)}`",
    "                    : \"\"}",
    "                </div>",
    "              </div>",
    "            </SettingRow>",
    "          )}",
    "        </Fragment>",
    "      ))}",
    "    </SettingGroup>",
    "  );",
    "}",
]
L[s:e + 1] = new_comp
with open(P, "w", encoding="utf-8", newline="") as f:
    f.write(nl.join(L))
print("component lines:", len(new_comp), "CRLF:", nl == "\r\n")
