/** 文件夹模块 API：对 core/tauri 的模块内收口 */
export {
  listFolders,
  addFolder,
  removeFolder,
  renameFolder,
  setFolderColor,
  toggleFolderPin,
  moveFolderToTop,
  reorderFolders,
  openFolder,
  openFolderInTerminal,
  openFolderInTerminalWith,
  openFolderInEditor,
  setVscodePath,
  pickVscodeExecutable,
  detectEditors,
  gitExec,
  folderGitBranches,
  copyFolderPath,
  pickFolder,
  setPanelAlwaysOnTop,
} from "../../core/tauri";
